# config/config.yaml
lifter_selector:
  expected_center: [0.5, 0.5]  # normalized coordinates (0 to 1) for the center of the frame
  roi: [0.3, 0.3, 0.7, 0.7]    # [x1, y1, x2, y2] normalized ROI bounds (optional)
  distance_weight: 1.0         # weight factor for the distance in the scoring function
  confidence_weight: 1.0       # weight factor for the confidence
